name: Generate ASCII Artwork

on: push

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name:  Exicute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon... RAWR" >> dragon.txt

    test_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: grep -i "drogon" dragon.txt

    deploy_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: read file
          run: cat dragon.txt
          
        - name: Deploy
          run: echo DePLOYINg...
